name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          args: -f
          root_file: CBB_Seminar_Presentation.tex
      - uses: actions/upload-artifact@v1
        with:
          name: pdf
          path: CBB_Seminar_Presentation.pdf