name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -f
          root_file: CBB_Seminar_Presentation.tex
      - uses: actions/upload-artifact
        with:
          name: pdf
          path: CBB_Seminar_Presentation.pdf